- name: SETUP_ROUTER
  hosts: router
  tasks:

    - name: "UPDATE_AND_UPGRADE"
      command: /bin/bash -c "apt-get update -y && apt-get upgrade -y"
      become: true
      become_user: root

    - name: "INSTALL_IFUPDOWN"
      command: /bin/bash -c "apt-get install ifupdown -y"
      become: true
      become_user: root
