- name: SETUP_ROUTER
  hosts: router
  tasks:

    - name: "UPDATE_AND_UPGRADE"
      apt:
        upgrade=yes
        update_cache=yes
        cache_valid_time=3600
      become: true
      become_user: root

    - name: "UNINSTALL_NETPLAN"
      apt:
        name: netplan
        update_cache: yes
        state: absent
      become: true
      become_user: root

    - name: "INSTALL_IFUPDOWN"
      apt:
        name: ifupdown
        update_cache: yes
      become: true
      become_user: root

    - name: "INSTALL_DHCP_SERVER"
      apt:
        name: isc-dhcp-server
        update_cache: yes
      become: true
      become_user: root

    - name: "INSTALL_IPTABLES_PERSISTENT"
      apt:
        name: iptables-persistent
        update_cache: yes
      become: true
      become_user: root

    - name: "INSTALL_NETFILTER_PERSISTENT"
      apt:
        name: netfilter-persistent
        update_cache: yes
      become: true
      become_user: root

    - name: "INSTALL_BIND9_DNS_SERVICE"
      apt:
        name: bind9
        update_cache: yes
      become: true
      become_user: root

    - name: "UPDATE_SYSCLT_CONFIG_FILE_FOR_IPFORWARDING"
      lineinfile: 
        path: /etc/sysctl.conf
        line: '{{ item }}'
      with_items:
        - "net.ipv4.ip_forward=1"
      become: true
      become_user: root

    - name: "DELETE_INTERFACES_FILE"
      file:
        path: /etc/network/interfaces
        state: absent
      become: true
      become_user: root

    - name: "CREATE_INTERFACES_FILE"
      file: 
        path: /etc/network/interfaces
        state: touch
      become: true
      become_user: root

    - name: "UPDATE_INTERFACES_FILE"
      lineinfile: 
        path: /etc/network/interfaces
        line: '{{ item }}'
      with_items:
        - "# The loopback network interface"
        - "auto lo"
        - "iface lo inet loopback"
        - " "
        - "# The WAN interface, motherboard interface"
        - "auto enp2s0"
        - "iface enp2s0 inet dhcp"
        - "  "
        - "# The LAN interface, pci express interface"
        - "auto enp1s0"
        - "iface enp1s0 inet static"
        - "\taddress 10.0.0.1"
        - "\tnetwork 10.0.0.0"
        - "\tnetmask 255.0.0.0"
        - "\tbroadcast 10.255.255.255"
      become: true
      become_user: root
    
    - name: "DELETE_STARTUP_SCRIPT_FILE"
      file:
        path: /etc/network/if-pre-up.d/iptables
        state: absent
      become: true
      become_user: root

    - name: "CREATE_STARTUP_SCRIPT_FILE"
      file: 
        path: /etc/network/if-pre-up.d/iptables
        state: touch
      become: true
      become_user: root

    - name: "CHANGE_STARTUP_SCRIPT_FILE_OWNER_WRITABLE_TO_ROOT_AND_READABLE_EXECUTABLE_BY_EVERYONE"
      file:  
        path: /etc/network/if-pre-up.d/iptables 
        owner: root
        mode: 0775
      become: true
      become_user: root

    - name: "UPDATE_STARTUP_SCRIPT_FILE"
      lineinfile: 
        path: /etc/network/if-pre-up.d/iptables
        line: '{{ item }}'
      with_items:
        - "#!/bin/sh"
        - "/sbin/iptables-restore < /etc/iptables/rules.v4"
      become: true
      become_user: root

    - name: "DELETE_STARTUP_SCRIPT_FILE"
      file:
        path: /etc/dhcp/dhcpd.conf
        state: absent
      become: true
      become_user: root

    - name: "CREATE_STARTUP_SCRIPT_FILE"
      file: 
        path: /etc/dhcp/dhcpd.conf
        state: touch
      become: true
      become_user: root

    - name: "CONFIGURE_DHCPD_CONF_SERVER_FILE"
      lineinfile: 
        path: /etc/dhcp/dhcpd.conf
        line: '{{ item }}'
      with_items:
        - ""
        - "default-lease-time 600;"
        - "max-lease-time 7200;"
        - "ddns-update-style none;"
        - "authoritative;"
        - "log-facility local7;"
        - " "
        - "host pi_vpn {"
        - "    hardware ethernet XX:XX:XX:XX:XX:XX;"
        - "    fixed-address 10.0.0.2;"
        - "}"
        - "  "
        - "host router_nas {"
        - "    hardware ethernet XX:XX:XX:XX:XX:XX;"
        - "    fixed-address 10.0.0.3;"
        - "} "
        - "   "
        - "subnet 10.0.0.0 netmask 255.0.0.0 {"
        - "  range 10.0.0.2 10.0.255.254;"
        - "  option routers 10.0.0.1;"
        - "  option domain-name-servers 10.0.0.1;"
        - "  option domain-name \"example.local\""
        - "  option broadcast-address 10.255.255.255;"
        - "}   "
      become: true
      become_user: root

    - name: "DELETE_BIND_NAME_CONF_OPTION_FILE"
      file:
        path: /etc/bind/named.conf.options
        state: absent
      become: true
      become_user: root

    - name: "CREATE_BIND_NAME_CONF_OPTION_FILE"
      file: 
        path: /etc/bind/named.conf.options
        state: touch
      become: true
      become_user: root

    - name: "UPDATE_BIND_NAME_CONF_OPTION_FILE"
      lineinfile: 
        path: /etc/bind/named.conf.options
        line: '{{ item }}'
      with_items:
        - "options {"
        - "\tdirectory \"/var/cache/bind\";"
        - ""
        - "\t// If there is a firewall between you and nameservers you want"
        - "\t// to talk to, you may need to fix the firewall to allow multiple"
        - "\t// ports to talk.  See http://www.kb.cert.org/vuls/id/800113"
        - " "
        - "\t// If your ISP provided one or more IP addresses for stable"
        - "\t// nameservers, you probably want to use them as forwarders."
        - "\t// Uncomment the following block, and insert the addresses replacing"
        - "\t// the all-0's placeholder."
        - "  "
        - "\t forwarders {"
        - "\t \t8.8.8.8;"
        - "\t \t8.8.4.4;"
        - "\t };"
        - "   "
        - "\t allow-query {"
        - "\t \t10.0.0.0/8;"
        - "\t \t127.0.0.1;"
        - "\t };"
        - "    "
        - "\t allow-transfer {"
        - "\t \t10.0.0.0/8;"
        - "\t \t127.0.0.1;"
        - "\t };"
        - "     "
        - "\t//========================================================================"
        - "\t// If BIND logs error messages about the root key being expired,"
        - "\t// you will need to update your keys.  See https://www.isc.org/bind-keys"
        - "\t//========================================================================"
        - "\tdnssec-validation auto;"
        - "      "
        - "\tauth-nxdomain no;    # conform to RFC1035"
        - "\tlisten-on-v6 { any; };"
        - "};"
      become: true
      become_user: root

    - name: "DELETE_IPTABLES_FILE"
      file:
        path: /etc/iptables/rules.v4
        state: absent
      become: true
      become_user: root

    - name: "CREATE_IPTABLES_FILE"
      file: 
        path: /etc/iptables/rules.v4
        state: touch
      become: true
      become_user: root

    - name: "UPDATE_IPTABLES_FILE"
      lineinfile: 
        path: /etc/iptables/rules.v4
        line: '{{ item }}'
        insertafter:
      with_items:
        - "###################################"
        - "############### NAT ###############"
        - "####################################"
        - "*nat"
        - ":PREROUTING ACCEPT [0:0]"
        - ":INPUT ACCEPT [0:0]"
        - ":OUTPUT ACCEPT [0:0]"
        - ":POSTROUTING ACCEPT [0:0]"
        - "#"
        - "# Enable NAT on WAN interface enp3s0"
        - "-A POSTROUTING -o enp2s0 -j MASQUERADE"
        - "##"
        - "#### Port Forwarding Section 1 - Add any port forwarding rules here and in Section 2 ####"
        - "# Example: Port forward HTTP traffic from WAN to LAN client 10.0.0.2"
        - "-A PREROUTING -p tcp -m tcp -i enp2s0 --dport 80 -j DNAT --to-destination 10.0.0.2:80"
        - "###"
        - "COMMIT"
        - ""
        - "*filter"
        - ":INPUT ACCEPT [0:0]#"
        - ":FORWARD ACCEPT [0:0]"
        - ":OUTPUT ACCEPT [0:0]#"
        - "####"
        - "##########################################"
        - "############### Services #################"
        - "###########################################"
        - "#####"
        - "# ICMP/Loopback - Accept all traffic from the router to itself (loopback) and ICMP (e.g. ping) traffic"
        - "-A INPUT -s 127.0.0.0/8 -d 127.0.0.0/8 -i lo -j ACCEPT"
        - "-A INPUT -p icmp -j ACCEPT"
        - "-A INPUT -m state --state ESTABLISHED -j ACCEPT"
        - "######"
        - "# Traceroute - Send a traceroute reject message instead of doing nothing when a client traceroute hits the router"
        - "-A INPUT -p udp -m udp --dport 33434:33523 -j REJECT --reject-with icmp-port-unreachable"
        - "#######"
        - "# DNS - Accept DNS requests traffic (port 53) from the private LAN interface"
        - "-A INPUT -i enp1s0 -p tcp --dport 53 -j ACCEPT"
        - "-A INPUT -i enp1s0 -p udp --dport 53 -j ACCEPT"
        - "########"
        - "# SSH - Accept SSH traffic (port 22) from the private LAN so we can manage the router from any machine on the private network"
        - "-A INPUT -i enp1s0 -p tcp --dport 22 -j ACCEPT"
        - "#########"
        - "# DHCP - Accept DHCP requests from the private LAN so that clients can get IP addresses from the router"
        - "-A INPUT -i enp1s0 -p udp --dport 67:68 -j ACCEPT"
        - "##########"
        - "# Drop any other traffic that hits the router"
        - "-A INPUT -j DROP"
        - "###########"
        - "#################################################"
        - "################ Forwarding rules ###############"
        - "##################################################"
        - "############"
        - "# forward packets to related/established connections"
        - "-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT"
        - "#############"
        - "# Forward from LAN enp2s0 interface to WAN enp3s0 interface"
        - "-A FORWARD -i enp1s0 -o enp2s0 -j ACCEPT"
        - "##############"
        - "#### Port Forwarding Section 2 - Add any port forwarding rules here and in Section 1 ####"
        - "# Example: Allow HTTP traffic from our NAT rule to client 10.0.0.2"
        - "-A FORWARD -p tcp -d 10.0.0.2 --dport 80 -j ACCEPT"
        - "###############"
        - "# drop all other forwarded traffic"
        - "-A FORWARD -j DROP"
        - "################"
        - "COMMIT#"
        - "####################################################"
      become: true
      become_user: root

    - name: "REPLACE_LINE_WORKAROUND"
      replace: 
        path: /etc/iptables/rules.v4
        regexp: 'COMMIT#'
        replace: 'COMMIT'
      become: true
      become_user: root

    - name: "REPLACE_LINE_WORKAROUND2"
      replace: 
        path: /etc/iptables/rules.v4
        regexp: ':INPUT ACCEPT \[0:0\]#'
        replace: ":INPUT ACCEPT [0:0]"
      become: true
      become_user: root

    - name: "REPLACE_LINE_WORKAROUND3"
      replace: 
        path: /etc/iptables/rules.v4
        regexp: ':OUTPUT ACCEPT \[0:0\]#'
        replace: ":OUTPUT ACCEPT [0:0]"
      become: true
      become_user: root

    - name: "REPLACE_LINE_WORKAROUND4"
      replace: 
        path: /etc/iptables/rules.v4
        regexp: '####################################################'
        replace: ''
      become: true
      become_user: root

    - name: "REBOOT"
      command: reboot
      become: true
      become_user: root

#    - name: "RESTART_NETWORK_INTERFACES"
#      command: systemctl restart networking.service
#      become: true
#      become_user: root

#    - name: "RESTART_BIND"
#      command: systemctl restart bind9
#      become: true
#      become_user: root

#    - name: "RESTART_DHCP_SERVER"
#      command: systemctl restart isc-dhcp-server
#      become: true
#      become_user: root
#
#    - name: "RESTART_IPTABLES"
#      command: systemctl restart netfilter-persistent
#      become: true
#      become_user: root

